name: Recovid++
paginate: 5
url: "https://rstephane.github.io/multilingual"
github-url: "https://rstephane.github.io/multilingual"
base-url: "/multilingual"
github-default-branch: "/edit/master/"
ga: "UA-71881194-1"

sass:
    style: compressed

timezone: Europe/Paris

defaults:
    -
     scope:
         path: ""
     values:
         author: "recovid"
         layout: post
         lang: en
         base-url: "https://rstephane.github.io/multilingual/"
    -
     scope:
         path: fr
     values:
         lang: fr
         base-url: "https://rstephane.github.io/multilingual/fr/"

gems: [
    "jekyll-paginate",
    "github-pages",
    "jekyll-sitemap"
]

# For travis
exclude: [vendor]

# Value to use into url per language
langs-value:
    en: ""
    fr: fr

# Translation
t:
    home:
        en: "Home"
        fr: "Accueil"
    project:
        en: "Project"
        fr: "Projets"
    about-me:
        en: "About me"
        fr: "À propos"
    contact:
        en: "Contact"
        fr: "Contact"
    subtitle:
        en: "My very own part of the Internet"
        fr: "Ma propre parcelle d'Internet"
    footer-article:
        en: "Found a mistake, or just want to add your words to this post ?"
        fr: "Vous avez trouvé une erreur ou souhaitez juste ajouter votre grain de sel ?"
    fork:
        en: "Fork it on github"
        fr: "Éditer sur github"
    desc:
        en: "My personnal website. recovid"
        fr: "Mon site personnel. recovid"
